#

CC=gcc  -m32
CFLAGS  = -DSOLARIS
LDFLAGS = -lthread -L/usr/openwin/lib -lX11 -ldl -lrt -lm



aos.solaris:	aos.o Threads.solaris.o
	$(CC) -s -o aos.solaris aos.o Threads.solaris.o $(LDFLAGS)
	rm -f *.o 

aos.o:	aos.c
	$(CC) -c $(CFLAGS) aos.c

Threads.solaris.o:	Threads.h Threads.solaris.c
	$(CC) -c $(CFLAGS) Threads.solaris.c 


